Improve CI workflow by adding exit status checks for MySQL and Nginx tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -283,15 +283,10 @@ jobs:
           exit 1
 
       - name: Test MySQL connection
-        run: docker exec mysql_ffb mysql -uroot -proot -e "SHOW DATABASES;" | grep -E 'ffb_main|ffb_stats|ffb_tests' || echo "One or more databases do not exist"
+        run: docker exec mysql_ffb mysql -uroot -proot -e "SHOW DATABASES;" | grep -E 'ffb_main|ffb_stats|ffb_tests' || echo "One or more databases do not exist" && exit 1
 
       - name: Test Nginx responds
-        run: curl -f http://localhost:7780
-          if [ $? -eq 0 ]; then
-              echo "Curl call was successful"
-          else
-              echo "Curl call failed"
-          fi
+        run: curl -f http://localhost:7780 && echo "Curl call was successful" || echo "Curl call failed" && exit 1
 
       - name: Test PHP service
         run: docker exec php_ffb php -v
