Update Nginx test URL in CI workflow to check stats endpoint

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -286,7 +286,7 @@ jobs:
         run: docker exec mysql_ffb mysql -uroot -proot -e "SHOW DATABASES;" | grep -E 'ffb_main|ffb_stats|ffb_tests' || echo "One or more databases do not exist"
 
       - name: Test Nginx responds
-        run: curl -f http://localhost:7780 && echo "Curl call was successful" || echo "Curl call failed"
+        run: curl -f http://localhost:7780/stats/ && echo "Curl call was successful" || echo "Curl call failed"
 
       - name: Test PHP service
         run: docker exec php_ffb php -v
